import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

// All 78 Tarot Cards
const cards = [
  // Major Arcana (22 cards)
  {
    slug: 'the-fool',
    nameEn: 'The Fool',
    nameRu: 'Шут',
    number: 0,
    arcana: 'MAJOR',
    suit: null,
    description: 'Шут символизирует начало нового пути, невинность и спонтанность. Эта карта говорит о готовности к новым приключениям без страха перед неизвестным.',
    uprightMeaning: 'Новые начинания, свобода, невинность, спонтанность, вера в жизнь. Время для прыжка в неизвестность с открытым сердцем.',
    reversedMeaning: 'Безрассудство, риск, наивность, необдуманные решения. Предупреждение о необходимости взвесить последствия своих действий.',
    uprightKeywords: JSON.stringify(['новое начало', 'свобода', 'приключение', 'спонтанность', 'невинность']),
    reversedKeywords: JSON.stringify(['безрассудство', 'риск', 'наивность', 'необдуманность']),
    imageUrl: '/cards/major/00-fool.jpg',
  },
  {
    slug: 'the-magician',
    nameEn: 'The Magician',
    nameRu: 'Маг',
    number: 1,
    arcana: 'MAJOR',
    suit: null,
    description: 'Маг представляет силу воли, мастерство и способность воплощать желания в реальность. У вас есть все инструменты для успеха.',
    uprightMeaning: 'Проявление, мастерство, сила воли, творчество. Все ресурсы в ваших руках для достижения целей.',
    reversedMeaning: 'Манипуляции, обман, нереализованный потенциал, неуверенность в своих способностях.',
    uprightKeywords: JSON.stringify(['воля', 'мастерство', 'творчество', 'проявление', 'сила']),
    reversedKeywords: JSON.stringify(['манипуляция', 'обман', 'неуверенность', 'нереализованность']),
    imageUrl: '/cards/major/01-magician.jpg',
  },
  {
    slug: 'the-high-priestess',
    nameEn: 'The High Priestess',
    nameRu: 'Верховная Жрица',
    number: 2,
    arcana: 'MAJOR',
    suit: null,
    description: 'Верховная Жрица хранит тайны и интуитивную мудрость. Она призывает прислушаться к внутреннему голосу.',
    uprightMeaning: 'Интуиция, тайны, подсознание, внутренняя мудрость. Доверяйте своему внутреннему голосу.',
    reversedMeaning: 'Скрытые мотивы, отключение от интуиции, поверхностность, секреты.',
    uprightKeywords: JSON.stringify(['интуиция', 'мудрость', 'тайны', 'подсознание', 'духовность']),
    reversedKeywords: JSON.stringify(['секретность', 'отключение', 'поверхностность', 'скрытое']),
    imageUrl: '/cards/major/02-high-priestess.jpg',
  },
  {
    slug: 'the-empress',
    nameEn: 'The Empress',
    nameRu: 'Императрица',
    number: 3,
    arcana: 'MAJOR',
    suit: null,
    description: 'Императрица олицетворяет плодородие, изобилие и материнскую заботу. Она символизирует творческую силу и красоту.',
    uprightMeaning: 'Плодородие, изобилие, красота, природа, материнство. Время процветания и творческого самовыражения.',
    reversedMeaning: 'Творческий блок, зависимость, пустота, проблемы с материнством.',
    uprightKeywords: JSON.stringify(['плодородие', 'изобилие', 'красота', 'природа', 'забота']),
    reversedKeywords: JSON.stringify(['блок', 'зависимость', 'пустота', 'небрежность']),
    imageUrl: '/cards/major/03-empress.jpg',
  },
  {
    slug: 'the-emperor',
    nameEn: 'The Emperor',
    nameRu: 'Император',
    number: 4,
    arcana: 'MAJOR',
    suit: null,
    description: 'Император символизирует власть, структуру и стабильность. Он представляет отцовскую фигуру и авторитет.',
    uprightMeaning: 'Власть, структура, контроль, отцовство, лидерство. Время для установления порядка и принятия ответственности.',
    reversedMeaning: 'Тирания, жесткость, отсутствие дисциплины, проблемы с авторитетом.',
    uprightKeywords: JSON.stringify(['власть', 'структура', 'лидерство', 'стабильность', 'контроль']),
    reversedKeywords: JSON.stringify(['тирания', 'жесткость', 'хаос', 'бессилие']),
    imageUrl: '/cards/major/04-emperor.jpg',
  },
  {
    slug: 'the-hierophant',
    nameEn: 'The Hierophant',
    nameRu: 'Иерофант',
    number: 5,
    arcana: 'MAJOR',
    suit: null,
    description: 'Иерофант представляет традиции, духовное наставничество и социальные институты.',
    uprightMeaning: 'Традиции, духовность, наставничество, конформизм. Следование проверенному пути и поиск духовного руководства.',
    reversedMeaning: 'Бунт против традиций, нетрадиционные подходы, личные убеждения.',
    uprightKeywords: JSON.stringify(['традиция', 'духовность', 'учение', 'мудрость', 'наставник']),
    reversedKeywords: JSON.stringify(['бунт', 'нетрадиционность', 'свобода', 'независимость']),
    imageUrl: '/cards/major/05-hierophant.jpg',
  },
  {
    slug: 'the-lovers',
    nameEn: 'The Lovers',
    nameRu: 'Влюблённые',
    number: 6,
    arcana: 'MAJOR',
    suit: null,
    description: 'Влюблённые символизируют любовь, гармонию и важные выборы в отношениях.',
    uprightMeaning: 'Любовь, гармония, отношения, выбор, ценности. Время для принятия решений сердцем.',
    reversedMeaning: 'Дисгармония, дисбаланс, неверный выбор, конфликт ценностей.',
    uprightKeywords: JSON.stringify(['любовь', 'гармония', 'выбор', 'партнёрство', 'единство']),
    reversedKeywords: JSON.stringify(['разлад', 'дисбаланс', 'конфликт', 'неверность']),
    imageUrl: '/cards/major/06-lovers.jpg',
  },
  {
    slug: 'the-chariot',
    nameEn: 'The Chariot',
    nameRu: 'Колесница',
    number: 7,
    arcana: 'MAJOR',
    suit: null,
    description: 'Колесница олицетворяет победу, решимость и преодоление препятствий силой воли.',
    uprightMeaning: 'Победа, решимость, контроль, движение вперёд. Преодоление препятствий через силу воли.',
    reversedMeaning: 'Отсутствие направления, агрессия, препятствия, потеря контроля.',
    uprightKeywords: JSON.stringify(['победа', 'решимость', 'контроль', 'движение', 'воля']),
    reversedKeywords: JSON.stringify(['застой', 'агрессия', 'препятствия', 'потеря']),
    imageUrl: '/cards/major/07-chariot.jpg',
  },
  {
    slug: 'strength',
    nameEn: 'Strength',
    nameRu: 'Сила',
    number: 8,
    arcana: 'MAJOR',
    suit: null,
    description: 'Сила представляет внутреннюю силу, смелость и способность мягко преодолевать трудности.',
    uprightMeaning: 'Внутренняя сила, смелость, терпение, сострадание. Победа через мягкость, а не агрессию.',
    reversedMeaning: 'Слабость, неуверенность, недостаток самоконтроля, страх.',
    uprightKeywords: JSON.stringify(['сила', 'смелость', 'терпение', 'сострадание', 'контроль']),
    reversedKeywords: JSON.stringify(['слабость', 'неуверенность', 'страх', 'сомнение']),
    imageUrl: '/cards/major/08-strength.jpg',
  },
  {
    slug: 'the-hermit',
    nameEn: 'The Hermit',
    nameRu: 'Отшельник',
    number: 9,
    arcana: 'MAJOR',
    suit: null,
    description: 'Отшельник символизирует поиск внутренней мудрости, уединение и самопознание.',
    uprightMeaning: 'Самопознание, уединение, внутренний поиск, мудрость. Время для размышлений и духовного роста.',
    reversedMeaning: 'Изоляция, одиночество, отстранённость, потеря пути.',
    uprightKeywords: JSON.stringify(['мудрость', 'уединение', 'поиск', 'размышление', 'наставничество']),
    reversedKeywords: JSON.stringify(['изоляция', 'одиночество', 'потерянность', 'отчуждение']),
    imageUrl: '/cards/major/09-hermit.jpg',
  },
  {
    slug: 'wheel-of-fortune',
    nameEn: 'Wheel of Fortune',
    nameRu: 'Колесо Фортуны',
    number: 10,
    arcana: 'MAJOR',
    suit: null,
    description: 'Колесо Фортуны представляет циклы жизни, судьбу и неожиданные повороты.',
    uprightMeaning: 'Удача, карма, циклы, судьба, поворотные моменты. Перемены к лучшему.',
    reversedMeaning: 'Неудача, сопротивление переменам, плохая карма, застой.',
    uprightKeywords: JSON.stringify(['судьба', 'удача', 'перемены', 'циклы', 'возможности']),
    reversedKeywords: JSON.stringify(['неудача', 'застой', 'сопротивление', 'невезение']),
    imageUrl: '/cards/major/10-wheel-of-fortune.jpg',
  },
  {
    slug: 'justice',
    nameEn: 'Justice',
    nameRu: 'Справедливость',
    number: 11,
    arcana: 'MAJOR',
    suit: null,
    description: 'Справедливость олицетворяет равновесие, честность и кармическое правосудие.',
    uprightMeaning: 'Справедливость, истина, баланс, закон, честность. Последствия прошлых действий.',
    reversedMeaning: 'Несправедливость, нечестность, дисбаланс, уклонение от ответственности.',
    uprightKeywords: JSON.stringify(['справедливость', 'баланс', 'истина', 'закон', 'карма']),
    reversedKeywords: JSON.stringify(['несправедливость', 'ложь', 'дисбаланс', 'уклонение']),
    imageUrl: '/cards/major/11-justice.jpg',
  },
  {
    slug: 'the-hanged-man',
    nameEn: 'The Hanged Man',
    nameRu: 'Повешенный',
    number: 12,
    arcana: 'MAJOR',
    suit: null,
    description: 'Повешенный символизирует жертву, новую перспективу и отпускание.',
    uprightMeaning: 'Жертва, новая перспектива, ожидание, отпускание. Время для паузы и пересмотра.',
    reversedMeaning: 'Застой, сопротивление, бесполезная жертва, нежелание отпустить.',
    uprightKeywords: JSON.stringify(['жертва', 'пауза', 'перспектива', 'отпускание', 'принятие']),
    reversedKeywords: JSON.stringify(['застой', 'сопротивление', 'упрямство', 'задержка']),
    imageUrl: '/cards/major/12-hanged-man.jpg',
  },
  {
    slug: 'death',
    nameEn: 'Death',
    nameRu: 'Смерть',
    number: 13,
    arcana: 'MAJOR',
    suit: null,
    description: 'Смерть представляет трансформацию, окончание и новые начинания через завершение старого.',
    uprightMeaning: 'Трансформация, окончание, перерождение, переход. Необходимые изменения для нового начала.',
    reversedMeaning: 'Сопротивление переменам, застой, страх перед неизвестным.',
    uprightKeywords: JSON.stringify(['трансформация', 'конец', 'перерождение', 'изменение', 'переход']),
    reversedKeywords: JSON.stringify(['сопротивление', 'застой', 'страх', 'неподвижность']),
    imageUrl: '/cards/major/13-death.jpg',
  },
  {
    slug: 'temperance',
    nameEn: 'Temperance',
    nameRu: 'Умеренность',
    number: 14,
    arcana: 'MAJOR',
    suit: null,
    description: 'Умеренность символизирует баланс, терпение и гармоничное слияние противоположностей.',
    uprightMeaning: 'Баланс, терпение, умеренность, гармония. Поиск золотой середины во всём.',
    reversedMeaning: 'Дисбаланс, избыток, нетерпение, отсутствие гармонии.',
    uprightKeywords: JSON.stringify(['баланс', 'терпение', 'гармония', 'умеренность', 'интеграция']),
    reversedKeywords: JSON.stringify(['дисбаланс', 'избыток', 'нетерпение', 'конфликт']),
    imageUrl: '/cards/major/14-temperance.jpg',
  },
  {
    slug: 'the-devil',
    nameEn: 'The Devil',
    nameRu: 'Дьявол',
    number: 15,
    arcana: 'MAJOR',
    suit: null,
    description: 'Дьявол представляет привязанности, зависимости и теневую сторону личности.',
    uprightMeaning: 'Привязанности, зависимости, материализм, теневая сторона. Осознание своих цепей.',
    reversedMeaning: 'Освобождение, преодоление зависимостей, восстановление контроля.',
    uprightKeywords: JSON.stringify(['привязанность', 'зависимость', 'тень', 'искушение', 'ограничение']),
    reversedKeywords: JSON.stringify(['освобождение', 'преодоление', 'разрыв', 'свобода']),
    imageUrl: '/cards/major/15-devil.jpg',
  },
  {
    slug: 'the-tower',
    nameEn: 'The Tower',
    nameRu: 'Башня',
    number: 16,
    arcana: 'MAJOR',
    suit: null,
    description: 'Башня символизирует внезапные перемены, разрушение и откровение.',
    uprightMeaning: 'Внезапные перемены, разрушение, откровение, хаос. Крушение ложных структур.',
    reversedMeaning: 'Избегание катастрофы, страх перед переменами, затянувшийся кризис.',
    uprightKeywords: JSON.stringify(['разрушение', 'перемены', 'хаос', 'откровение', 'освобождение']),
    reversedKeywords: JSON.stringify(['избегание', 'страх', 'затяжной кризис', 'отрицание']),
    imageUrl: '/cards/major/16-tower.jpg',
  },
  {
    slug: 'the-star',
    nameEn: 'The Star',
    nameRu: 'Звезда',
    number: 17,
    arcana: 'MAJOR',
    suit: null,
    description: 'Звезда несёт надежду, вдохновение и духовное обновление после трудных времён.',
    uprightMeaning: 'Надежда, вдохновение, обновление, спокойствие. Свет в конце туннеля.',
    reversedMeaning: 'Отчаяние, потеря веры, разочарование, отсутствие вдохновения.',
    uprightKeywords: JSON.stringify(['надежда', 'вдохновение', 'обновление', 'вера', 'исцеление']),
    reversedKeywords: JSON.stringify(['отчаяние', 'потеря веры', 'разочарование', 'пустота']),
    imageUrl: '/cards/major/17-star.jpg',
  },
  {
    slug: 'the-moon',
    nameEn: 'The Moon',
    nameRu: 'Луна',
    number: 18,
    arcana: 'MAJOR',
    suit: null,
    description: 'Луна представляет интуицию, иллюзии и путешествие в подсознание.',
    uprightMeaning: 'Интуиция, иллюзии, подсознание, страхи. Время довериться интуиции и пройти через неизвестность.',
    reversedMeaning: 'Путаница, обман, преодоление страхов, ясность после иллюзий.',
    uprightKeywords: JSON.stringify(['интуиция', 'иллюзии', 'подсознание', 'тайны', 'страхи']),
    reversedKeywords: JSON.stringify(['путаница', 'обман', 'ясность', 'преодоление']),
    imageUrl: '/cards/major/18-moon.jpg',
  },
  {
    slug: 'the-sun',
    nameEn: 'The Sun',
    nameRu: 'Солнце',
    number: 19,
    arcana: 'MAJOR',
    suit: null,
    description: 'Солнце приносит радость, успех и ясность. Одна из самых позитивных карт Таро.',
    uprightMeaning: 'Радость, успех, ясность, позитив, изобилие. Время праздновать жизнь!',
    reversedMeaning: 'Временные задержки, сниженный оптимизм, поиск внутреннего ребёнка.',
    uprightKeywords: JSON.stringify(['радость', 'успех', 'ясность', 'позитив', 'витальность']),
    reversedKeywords: JSON.stringify(['задержки', 'пессимизм', 'неясность', 'блокировка']),
    imageUrl: '/cards/major/19-sun.jpg',
  },
  {
    slug: 'judgement',
    nameEn: 'Judgement',
    nameRu: 'Суд',
    number: 20,
    arcana: 'MAJOR',
    suit: null,
    description: 'Суд символизирует возрождение, призвание и самооценку прошлых действий.',
    uprightMeaning: 'Возрождение, призвание, самооценка, пробуждение. Время ответить на внутренний зов.',
    reversedMeaning: 'Самокритика, сомнение, отказ от призвания, застревание в прошлом.',
    uprightKeywords: JSON.stringify(['возрождение', 'призвание', 'пробуждение', 'оценка', 'решение']),
    reversedKeywords: JSON.stringify(['самокритика', 'сомнение', 'отказ', 'застой']),
    imageUrl: '/cards/major/20-judgement.jpg',
  },
  {
    slug: 'the-world',
    nameEn: 'The World',
    nameRu: 'Мир',
    number: 21,
    arcana: 'MAJOR',
    suit: null,
    description: 'Мир представляет завершение цикла, целостность и достижение целей.',
    uprightMeaning: 'Завершение, достижение, целостность, интеграция. Финал важного этапа жизни.',
    reversedMeaning: 'Незавершённость, поиск завершения, задержки, неполнота.',
    uprightKeywords: JSON.stringify(['завершение', 'целостность', 'достижение', 'интеграция', 'успех']),
    reversedKeywords: JSON.stringify(['незавершённость', 'задержки', 'неполнота', 'стагнация']),
    imageUrl: '/cards/major/21-world.jpg',
  },

  // Minor Arcana - Wands
  { slug: 'ace-of-wands', nameEn: 'Ace of Wands', nameRu: 'Туз Жезлов', number: 1, arcana: 'MINOR', suit: 'WANDS', description: 'Туз Жезлов символизирует новые творческие начинания, вдохновение и потенциал.', uprightMeaning: 'Новое начало, вдохновение, потенциал, творчество.', reversedMeaning: 'Задержки, отсутствие направления, творческий блок.', uprightKeywords: JSON.stringify(['начало', 'вдохновение', 'потенциал']), reversedKeywords: JSON.stringify(['задержка', 'блок', 'застой']), imageUrl: '/cards/wands/01-ace.jpg' },
  { slug: 'two-of-wands', nameEn: 'Two of Wands', nameRu: 'Двойка Жезлов', number: 2, arcana: 'MINOR', suit: 'WANDS', description: 'Планирование будущего и принятие решений.', uprightMeaning: 'Планирование, решения, прогресс.', reversedMeaning: 'Страх перемен, нерешительность.', uprightKeywords: JSON.stringify(['планирование', 'решения']), reversedKeywords: JSON.stringify(['страх', 'нерешительность']), imageUrl: '/cards/wands/02-two.jpg' },
  { slug: 'three-of-wands', nameEn: 'Three of Wands', nameRu: 'Тройка Жезлов', number: 3, arcana: 'MINOR', suit: 'WANDS', description: 'Расширение горизонтов и ожидание результатов.', uprightMeaning: 'Расширение, дальновидность, прогресс.', reversedMeaning: 'Препятствия, задержки.', uprightKeywords: JSON.stringify(['расширение', 'прогресс']), reversedKeywords: JSON.stringify(['препятствия', 'задержки']), imageUrl: '/cards/wands/03-three.jpg' },
  { slug: 'four-of-wands', nameEn: 'Four of Wands', nameRu: 'Четвёрка Жезлов', number: 4, arcana: 'MINOR', suit: 'WANDS', description: 'Празднование, гармония и достижение.', uprightMeaning: 'Празднование, гармония, стабильность.', reversedMeaning: 'Дисгармония, незавершённость.', uprightKeywords: JSON.stringify(['празднование', 'гармония']), reversedKeywords: JSON.stringify(['дисгармония']), imageUrl: '/cards/wands/04-four.jpg' },
  { slug: 'five-of-wands', nameEn: 'Five of Wands', nameRu: 'Пятёрка Жезлов', number: 5, arcana: 'MINOR', suit: 'WANDS', description: 'Конфликты и конкуренция.', uprightMeaning: 'Конфликт, конкуренция, споры.', reversedMeaning: 'Избегание конфликта, разрешение.', uprightKeywords: JSON.stringify(['конфликт', 'конкуренция']), reversedKeywords: JSON.stringify(['разрешение']), imageUrl: '/cards/wands/05-five.jpg' },
  { slug: 'six-of-wands', nameEn: 'Six of Wands', nameRu: 'Шестёрка Жезлов', number: 6, arcana: 'MINOR', suit: 'WANDS', description: 'Победа и признание.', uprightMeaning: 'Победа, успех, признание.', reversedMeaning: 'Провал, непризнание.', uprightKeywords: JSON.stringify(['победа', 'успех']), reversedKeywords: JSON.stringify(['провал']), imageUrl: '/cards/wands/06-six.jpg' },
  { slug: 'seven-of-wands', nameEn: 'Seven of Wands', nameRu: 'Семёрка Жезлов', number: 7, arcana: 'MINOR', suit: 'WANDS', description: 'Защита позиций.', uprightMeaning: 'Защита, настойчивость.', reversedMeaning: 'Сдача позиций, истощение.', uprightKeywords: JSON.stringify(['защита', 'настойчивость']), reversedKeywords: JSON.stringify(['истощение']), imageUrl: '/cards/wands/07-seven.jpg' },
  { slug: 'eight-of-wands', nameEn: 'Eight of Wands', nameRu: 'Восьмёрка Жезлов', number: 8, arcana: 'MINOR', suit: 'WANDS', description: 'Быстрое движение и прогресс.', uprightMeaning: 'Скорость, прогресс, движение.', reversedMeaning: 'Задержки, замедление.', uprightKeywords: JSON.stringify(['скорость', 'прогресс']), reversedKeywords: JSON.stringify(['задержки']), imageUrl: '/cards/wands/08-eight.jpg' },
  { slug: 'nine-of-wands', nameEn: 'Nine of Wands', nameRu: 'Девятка Жезлов', number: 9, arcana: 'MINOR', suit: 'WANDS', description: 'Стойкость и выносливость.', uprightMeaning: 'Стойкость, выносливость.', reversedMeaning: 'Истощение, паранойя.', uprightKeywords: JSON.stringify(['стойкость']), reversedKeywords: JSON.stringify(['истощение']), imageUrl: '/cards/wands/09-nine.jpg' },
  { slug: 'ten-of-wands', nameEn: 'Ten of Wands', nameRu: 'Десятка Жезлов', number: 10, arcana: 'MINOR', suit: 'WANDS', description: 'Бремя и ответственность.', uprightMeaning: 'Бремя, ответственность.', reversedMeaning: 'Делегирование, облегчение.', uprightKeywords: JSON.stringify(['бремя']), reversedKeywords: JSON.stringify(['облегчение']), imageUrl: '/cards/wands/10-ten.jpg' },
  { slug: 'page-of-wands', nameEn: 'Page of Wands', nameRu: 'Паж Жезлов', number: 11, arcana: 'MINOR', suit: 'WANDS', description: 'Энтузиазм и новые идеи.', uprightMeaning: 'Энтузиазм, исследование.', reversedMeaning: 'Незрелость, задержки.', uprightKeywords: JSON.stringify(['энтузиазм']), reversedKeywords: JSON.stringify(['незрелость']), imageUrl: '/cards/wands/11-page.jpg' },
  { slug: 'knight-of-wands', nameEn: 'Knight of Wands', nameRu: 'Рыцарь Жезлов', number: 12, arcana: 'MINOR', suit: 'WANDS', description: 'Энергия и страсть.', uprightMeaning: 'Энергия, страсть, действие.', reversedMeaning: 'Импульсивность.', uprightKeywords: JSON.stringify(['энергия', 'страсть']), reversedKeywords: JSON.stringify(['импульсивность']), imageUrl: '/cards/wands/12-knight.jpg' },
  { slug: 'queen-of-wands', nameEn: 'Queen of Wands', nameRu: 'Королева Жезлов', number: 13, arcana: 'MINOR', suit: 'WANDS', description: 'Уверенность и харизма.', uprightMeaning: 'Уверенность, независимость.', reversedMeaning: 'Эгоизм, ревность.', uprightKeywords: JSON.stringify(['уверенность']), reversedKeywords: JSON.stringify(['эгоизм']), imageUrl: '/cards/wands/13-queen.jpg' },
  { slug: 'king-of-wands', nameEn: 'King of Wands', nameRu: 'Король Жезлов', number: 14, arcana: 'MINOR', suit: 'WANDS', description: 'Лидерство и видение.', uprightMeaning: 'Лидерство, видение.', reversedMeaning: 'Тирания, высокомерие.', uprightKeywords: JSON.stringify(['лидерство']), reversedKeywords: JSON.stringify(['тирания']), imageUrl: '/cards/wands/14-king.jpg' },

  // Minor Arcana - Cups
  { slug: 'ace-of-cups', nameEn: 'Ace of Cups', nameRu: 'Туз Кубков', number: 1, arcana: 'MINOR', suit: 'CUPS', description: 'Новая любовь и эмоции.', uprightMeaning: 'Новая любовь, эмоции, интуиция.', reversedMeaning: 'Эмоциональная блокировка.', uprightKeywords: JSON.stringify(['любовь', 'эмоции']), reversedKeywords: JSON.stringify(['блокировка']), imageUrl: '/cards/cups/01-ace.jpg' },
  { slug: 'two-of-cups', nameEn: 'Two of Cups', nameRu: 'Двойка Кубков', number: 2, arcana: 'MINOR', suit: 'CUPS', description: 'Партнёрство и любовь.', uprightMeaning: 'Партнёрство, любовь, гармония.', reversedMeaning: 'Дисбаланс, разрыв.', uprightKeywords: JSON.stringify(['партнёрство', 'любовь']), reversedKeywords: JSON.stringify(['разрыв']), imageUrl: '/cards/cups/02-two.jpg' },
  { slug: 'three-of-cups', nameEn: 'Three of Cups', nameRu: 'Тройка Кубков', number: 3, arcana: 'MINOR', suit: 'CUPS', description: 'Праздник и дружба.', uprightMeaning: 'Праздник, дружба, радость.', reversedMeaning: 'Избыток, сплетни.', uprightKeywords: JSON.stringify(['праздник', 'дружба']), reversedKeywords: JSON.stringify(['сплетни']), imageUrl: '/cards/cups/03-three.jpg' },
  { slug: 'four-of-cups', nameEn: 'Four of Cups', nameRu: 'Четвёрка Кубков', number: 4, arcana: 'MINOR', suit: 'CUPS', description: 'Апатия и медитация.', uprightMeaning: 'Апатия, медитация.', reversedMeaning: 'Мотивация, принятие.', uprightKeywords: JSON.stringify(['апатия']), reversedKeywords: JSON.stringify(['мотивация']), imageUrl: '/cards/cups/04-four.jpg' },
  { slug: 'five-of-cups', nameEn: 'Five of Cups', nameRu: 'Пятёрка Кубков', number: 5, arcana: 'MINOR', suit: 'CUPS', description: 'Потеря и сожаление.', uprightMeaning: 'Потеря, сожаление, горе.', reversedMeaning: 'Принятие, прощение.', uprightKeywords: JSON.stringify(['потеря', 'горе']), reversedKeywords: JSON.stringify(['прощение']), imageUrl: '/cards/cups/05-five.jpg' },
  { slug: 'six-of-cups', nameEn: 'Six of Cups', nameRu: 'Шестёрка Кубков', number: 6, arcana: 'MINOR', suit: 'CUPS', description: 'Ностальгия и воспоминания.', uprightMeaning: 'Ностальгия, невинность.', reversedMeaning: 'Застревание в прошлом.', uprightKeywords: JSON.stringify(['ностальгия']), reversedKeywords: JSON.stringify(['прошлое']), imageUrl: '/cards/cups/06-six.jpg' },
  { slug: 'seven-of-cups', nameEn: 'Seven of Cups', nameRu: 'Семёрка Кубков', number: 7, arcana: 'MINOR', suit: 'CUPS', description: 'Фантазии и выбор.', uprightMeaning: 'Фантазии, выбор, иллюзии.', reversedMeaning: 'Ясность, решение.', uprightKeywords: JSON.stringify(['фантазии', 'выбор']), reversedKeywords: JSON.stringify(['ясность']), imageUrl: '/cards/cups/07-seven.jpg' },
  { slug: 'eight-of-cups', nameEn: 'Eight of Cups', nameRu: 'Восьмёрка Кубков', number: 8, arcana: 'MINOR', suit: 'CUPS', description: 'Уход и поиск.', uprightMeaning: 'Уход, отказ, поиск.', reversedMeaning: 'Страх перемен.', uprightKeywords: JSON.stringify(['уход', 'поиск']), reversedKeywords: JSON.stringify(['страх']), imageUrl: '/cards/cups/08-eight.jpg' },
  { slug: 'nine-of-cups', nameEn: 'Nine of Cups', nameRu: 'Девятка Кубков', number: 9, arcana: 'MINOR', suit: 'CUPS', description: 'Удовлетворение и счастье.', uprightMeaning: 'Удовлетворение, счастье.', reversedMeaning: 'Неудовлетворённость.', uprightKeywords: JSON.stringify(['счастье']), reversedKeywords: JSON.stringify(['неудовлетворённость']), imageUrl: '/cards/cups/09-nine.jpg' },
  { slug: 'ten-of-cups', nameEn: 'Ten of Cups', nameRu: 'Десятка Кубков', number: 10, arcana: 'MINOR', suit: 'CUPS', description: 'Семейное счастье.', uprightMeaning: 'Семейное счастье, гармония.', reversedMeaning: 'Семейные проблемы.', uprightKeywords: JSON.stringify(['семья', 'счастье']), reversedKeywords: JSON.stringify(['проблемы']), imageUrl: '/cards/cups/10-ten.jpg' },
  { slug: 'page-of-cups', nameEn: 'Page of Cups', nameRu: 'Паж Кубков', number: 11, arcana: 'MINOR', suit: 'CUPS', description: 'Творчество и интуиция.', uprightMeaning: 'Творчество, интуиция.', reversedMeaning: 'Незрелость.', uprightKeywords: JSON.stringify(['творчество']), reversedKeywords: JSON.stringify(['незрелость']), imageUrl: '/cards/cups/11-page.jpg' },
  { slug: 'knight-of-cups', nameEn: 'Knight of Cups', nameRu: 'Рыцарь Кубков', number: 12, arcana: 'MINOR', suit: 'CUPS', description: 'Романтика и красота.', uprightMeaning: 'Романтика, творчество.', reversedMeaning: 'Нереалистичность.', uprightKeywords: JSON.stringify(['романтика']), reversedKeywords: JSON.stringify(['нереалистичность']), imageUrl: '/cards/cups/12-knight.jpg' },
  { slug: 'queen-of-cups', nameEn: 'Queen of Cups', nameRu: 'Королева Кубков', number: 13, arcana: 'MINOR', suit: 'CUPS', description: 'Интуиция и сострадание.', uprightMeaning: 'Интуиция, сострадание.', reversedMeaning: 'Нестабильность.', uprightKeywords: JSON.stringify(['интуиция']), reversedKeywords: JSON.stringify(['нестабильность']), imageUrl: '/cards/cups/13-queen.jpg' },
  { slug: 'king-of-cups', nameEn: 'King of Cups', nameRu: 'Король Кубков', number: 14, arcana: 'MINOR', suit: 'CUPS', description: 'Эмоциональный баланс.', uprightMeaning: 'Баланс, мудрость.', reversedMeaning: 'Манипуляция.', uprightKeywords: JSON.stringify(['баланс']), reversedKeywords: JSON.stringify(['манипуляция']), imageUrl: '/cards/cups/14-king.jpg' },

  // Minor Arcana - Swords
  { slug: 'ace-of-swords', nameEn: 'Ace of Swords', nameRu: 'Туз Мечей', number: 1, arcana: 'MINOR', suit: 'SWORDS', description: 'Ясность и прорыв.', uprightMeaning: 'Ясность, прорыв, истина.', reversedMeaning: 'Путаница, хаос.', uprightKeywords: JSON.stringify(['ясность', 'истина']), reversedKeywords: JSON.stringify(['путаница']), imageUrl: '/cards/swords/01-ace.jpg' },
  { slug: 'two-of-swords', nameEn: 'Two of Swords', nameRu: 'Двойка Мечей', number: 2, arcana: 'MINOR', suit: 'SWORDS', description: 'Тупик и выбор.', uprightMeaning: 'Тупик, выбор, баланс.', reversedMeaning: 'Нерешительность.', uprightKeywords: JSON.stringify(['выбор']), reversedKeywords: JSON.stringify(['нерешительность']), imageUrl: '/cards/swords/02-two.jpg' },
  { slug: 'three-of-swords', nameEn: 'Three of Swords', nameRu: 'Тройка Мечей', number: 3, arcana: 'MINOR', suit: 'SWORDS', description: 'Сердечная боль.', uprightMeaning: 'Боль, горе, предательство.', reversedMeaning: 'Исцеление, прощение.', uprightKeywords: JSON.stringify(['боль', 'горе']), reversedKeywords: JSON.stringify(['исцеление']), imageUrl: '/cards/swords/03-three.jpg' },
  { slug: 'four-of-swords', nameEn: 'Four of Swords', nameRu: 'Четвёрка Мечей', number: 4, arcana: 'MINOR', suit: 'SWORDS', description: 'Отдых и восстановление.', uprightMeaning: 'Отдых, восстановление.', reversedMeaning: 'Беспокойство.', uprightKeywords: JSON.stringify(['отдых']), reversedKeywords: JSON.stringify(['беспокойство']), imageUrl: '/cards/swords/04-four.jpg' },
  { slug: 'five-of-swords', nameEn: 'Five of Swords', nameRu: 'Пятёрка Мечей', number: 5, arcana: 'MINOR', suit: 'SWORDS', description: 'Конфликт и поражение.', uprightMeaning: 'Конфликт, поражение.', reversedMeaning: 'Примирение.', uprightKeywords: JSON.stringify(['конфликт']), reversedKeywords: JSON.stringify(['примирение']), imageUrl: '/cards/swords/05-five.jpg' },
  { slug: 'six-of-swords', nameEn: 'Six of Swords', nameRu: 'Шестёрка Мечей', number: 6, arcana: 'MINOR', suit: 'SWORDS', description: 'Переход и уход.', uprightMeaning: 'Переход, исцеление.', reversedMeaning: 'Застревание.', uprightKeywords: JSON.stringify(['переход']), reversedKeywords: JSON.stringify(['застревание']), imageUrl: '/cards/swords/06-six.jpg' },
  { slug: 'seven-of-swords', nameEn: 'Seven of Swords', nameRu: 'Семёрка Мечей', number: 7, arcana: 'MINOR', suit: 'SWORDS', description: 'Хитрость и обман.', uprightMeaning: 'Хитрость, стратегия.', reversedMeaning: 'Разоблачение.', uprightKeywords: JSON.stringify(['хитрость']), reversedKeywords: JSON.stringify(['разоблачение']), imageUrl: '/cards/swords/07-seven.jpg' },
  { slug: 'eight-of-swords', nameEn: 'Eight of Swords', nameRu: 'Восьмёрка Мечей', number: 8, arcana: 'MINOR', suit: 'SWORDS', description: 'Ограничения и страхи.', uprightMeaning: 'Ограничения, страхи.', reversedMeaning: 'Освобождение.', uprightKeywords: JSON.stringify(['ограничения']), reversedKeywords: JSON.stringify(['освобождение']), imageUrl: '/cards/swords/08-eight.jpg' },
  { slug: 'nine-of-swords', nameEn: 'Nine of Swords', nameRu: 'Девятка Мечей', number: 9, arcana: 'MINOR', suit: 'SWORDS', description: 'Тревога и кошмары.', uprightMeaning: 'Тревога, страх.', reversedMeaning: 'Облегчение.', uprightKeywords: JSON.stringify(['тревога']), reversedKeywords: JSON.stringify(['облегчение']), imageUrl: '/cards/swords/09-nine.jpg' },
  { slug: 'ten-of-swords', nameEn: 'Ten of Swords', nameRu: 'Десятка Мечей', number: 10, arcana: 'MINOR', suit: 'SWORDS', description: 'Конец и предательство.', uprightMeaning: 'Конец, предательство.', reversedMeaning: 'Восстановление.', uprightKeywords: JSON.stringify(['конец']), reversedKeywords: JSON.stringify(['восстановление']), imageUrl: '/cards/swords/10-ten.jpg' },
  { slug: 'page-of-swords', nameEn: 'Page of Swords', nameRu: 'Паж Мечей', number: 11, arcana: 'MINOR', suit: 'SWORDS', description: 'Любопытство и идеи.', uprightMeaning: 'Любопытство, идеи.', reversedMeaning: 'Сплетни.', uprightKeywords: JSON.stringify(['любопытство']), reversedKeywords: JSON.stringify(['сплетни']), imageUrl: '/cards/swords/11-page.jpg' },
  { slug: 'knight-of-swords', nameEn: 'Knight of Swords', nameRu: 'Рыцарь Мечей', number: 12, arcana: 'MINOR', suit: 'SWORDS', description: 'Амбиции и действие.', uprightMeaning: 'Амбиции, решительность.', reversedMeaning: 'Безрассудство.', uprightKeywords: JSON.stringify(['амбиции']), reversedKeywords: JSON.stringify(['безрассудство']), imageUrl: '/cards/swords/12-knight.jpg' },
  { slug: 'queen-of-swords', nameEn: 'Queen of Swords', nameRu: 'Королева Мечей', number: 13, arcana: 'MINOR', suit: 'SWORDS', description: 'Ясность и независимость.', uprightMeaning: 'Ясность, независимость.', reversedMeaning: 'Холодность.', uprightKeywords: JSON.stringify(['ясность']), reversedKeywords: JSON.stringify(['холодность']), imageUrl: '/cards/swords/13-queen.jpg' },
  { slug: 'king-of-swords', nameEn: 'King of Swords', nameRu: 'Король Мечей', number: 14, arcana: 'MINOR', suit: 'SWORDS', description: 'Интеллект и авторитет.', uprightMeaning: 'Интеллект, авторитет.', reversedMeaning: 'Манипуляции.', uprightKeywords: JSON.stringify(['интеллект']), reversedKeywords: JSON.stringify(['манипуляции']), imageUrl: '/cards/swords/14-king.jpg' },

  // Minor Arcana - Pentacles
  { slug: 'ace-of-pentacles', nameEn: 'Ace of Pentacles', nameRu: 'Туз Пентаклей', number: 1, arcana: 'MINOR', suit: 'PENTACLES', description: 'Новые возможности.', uprightMeaning: 'Возможности, процветание.', reversedMeaning: 'Упущенные шансы.', uprightKeywords: JSON.stringify(['возможности']), reversedKeywords: JSON.stringify(['упущение']), imageUrl: '/cards/pentacles/01-ace.jpg' },
  { slug: 'two-of-pentacles', nameEn: 'Two of Pentacles', nameRu: 'Двойка Пентаклей', number: 2, arcana: 'MINOR', suit: 'PENTACLES', description: 'Баланс и адаптация.', uprightMeaning: 'Баланс, адаптация.', reversedMeaning: 'Дисбаланс.', uprightKeywords: JSON.stringify(['баланс']), reversedKeywords: JSON.stringify(['дисбаланс']), imageUrl: '/cards/pentacles/02-two.jpg' },
  { slug: 'three-of-pentacles', nameEn: 'Three of Pentacles', nameRu: 'Тройка Пентаклей', number: 3, arcana: 'MINOR', suit: 'PENTACLES', description: 'Командная работа.', uprightMeaning: 'Команда, мастерство.', reversedMeaning: 'Разногласия.', uprightKeywords: JSON.stringify(['команда']), reversedKeywords: JSON.stringify(['разногласия']), imageUrl: '/cards/pentacles/03-three.jpg' },
  { slug: 'four-of-pentacles', nameEn: 'Four of Pentacles', nameRu: 'Четвёрка Пентаклей', number: 4, arcana: 'MINOR', suit: 'PENTACLES', description: 'Безопасность и контроль.', uprightMeaning: 'Безопасность, стабильность.', reversedMeaning: 'Жадность.', uprightKeywords: JSON.stringify(['безопасность']), reversedKeywords: JSON.stringify(['жадность']), imageUrl: '/cards/pentacles/04-four.jpg' },
  { slug: 'five-of-pentacles', nameEn: 'Five of Pentacles', nameRu: 'Пятёрка Пентаклей', number: 5, arcana: 'MINOR', suit: 'PENTACLES', description: 'Трудности и нужда.', uprightMeaning: 'Трудности, изоляция.', reversedMeaning: 'Восстановление.', uprightKeywords: JSON.stringify(['трудности']), reversedKeywords: JSON.stringify(['восстановление']), imageUrl: '/cards/pentacles/05-five.jpg' },
  { slug: 'six-of-pentacles', nameEn: 'Six of Pentacles', nameRu: 'Шестёрка Пентаклей', number: 6, arcana: 'MINOR', suit: 'PENTACLES', description: 'Щедрость и баланс.', uprightMeaning: 'Щедрость, помощь.', reversedMeaning: 'Долги.', uprightKeywords: JSON.stringify(['щедрость']), reversedKeywords: JSON.stringify(['долги']), imageUrl: '/cards/pentacles/06-six.jpg' },
  { slug: 'seven-of-pentacles', nameEn: 'Seven of Pentacles', nameRu: 'Семёрка Пентаклей', number: 7, arcana: 'MINOR', suit: 'PENTACLES', description: 'Терпение и оценка.', uprightMeaning: 'Терпение, инвестиции.', reversedMeaning: 'Нетерпение.', uprightKeywords: JSON.stringify(['терпение']), reversedKeywords: JSON.stringify(['нетерпение']), imageUrl: '/cards/pentacles/07-seven.jpg' },
  { slug: 'eight-of-pentacles', nameEn: 'Eight of Pentacles', nameRu: 'Восьмёрка Пентаклей', number: 8, arcana: 'MINOR', suit: 'PENTACLES', description: 'Усердие и мастерство.', uprightMeaning: 'Усердие, обучение.', reversedMeaning: 'Рутина.', uprightKeywords: JSON.stringify(['усердие']), reversedKeywords: JSON.stringify(['рутина']), imageUrl: '/cards/pentacles/08-eight.jpg' },
  { slug: 'nine-of-pentacles', nameEn: 'Nine of Pentacles', nameRu: 'Девятка Пентаклей', number: 9, arcana: 'MINOR', suit: 'PENTACLES', description: 'Изобилие и независимость.', uprightMeaning: 'Изобилие, роскошь.', reversedMeaning: 'Зависимость.', uprightKeywords: JSON.stringify(['изобилие']), reversedKeywords: JSON.stringify(['зависимость']), imageUrl: '/cards/pentacles/09-nine.jpg' },
  { slug: 'ten-of-pentacles', nameEn: 'Ten of Pentacles', nameRu: 'Десятка Пентаклей', number: 10, arcana: 'MINOR', suit: 'PENTACLES', description: 'Семейное богатство.', uprightMeaning: 'Богатство, наследство.', reversedMeaning: 'Споры.', uprightKeywords: JSON.stringify(['богатство']), reversedKeywords: JSON.stringify(['споры']), imageUrl: '/cards/pentacles/10-ten.jpg' },
  { slug: 'page-of-pentacles', nameEn: 'Page of Pentacles', nameRu: 'Паж Пентаклей', number: 11, arcana: 'MINOR', suit: 'PENTACLES', description: 'Возможности и обучение.', uprightMeaning: 'Возможности, амбиции.', reversedMeaning: 'Прокрастинация.', uprightKeywords: JSON.stringify(['возможности']), reversedKeywords: JSON.stringify(['прокрастинация']), imageUrl: '/cards/pentacles/11-page.jpg' },
  { slug: 'knight-of-pentacles', nameEn: 'Knight of Pentacles', nameRu: 'Рыцарь Пентаклей', number: 12, arcana: 'MINOR', suit: 'PENTACLES', description: 'Надёжность и труд.', uprightMeaning: 'Надёжность, трудолюбие.', reversedMeaning: 'Застой.', uprightKeywords: JSON.stringify(['надёжность']), reversedKeywords: JSON.stringify(['застой']), imageUrl: '/cards/pentacles/12-knight.jpg' },
  { slug: 'queen-of-pentacles', nameEn: 'Queen of Pentacles', nameRu: 'Королева Пентаклей', number: 13, arcana: 'MINOR', suit: 'PENTACLES', description: 'Практичность и забота.', uprightMeaning: 'Практичность, комфорт.', reversedMeaning: 'Материализм.', uprightKeywords: JSON.stringify(['практичность']), reversedKeywords: JSON.stringify(['материализм']), imageUrl: '/cards/pentacles/13-queen.jpg' },
  { slug: 'king-of-pentacles', nameEn: 'King of Pentacles', nameRu: 'Король Пентаклей', number: 14, arcana: 'MINOR', suit: 'PENTACLES', description: 'Финансовый успех.', uprightMeaning: 'Успех, надёжность.', reversedMeaning: 'Жадность.', uprightKeywords: JSON.stringify(['успех']), reversedKeywords: JSON.stringify(['жадность']), imageUrl: '/cards/pentacles/14-king.jpg' },
]

// Achievement definitions
const achievements = [
  { code: 'FIRST_READING', name: 'Первый шаг', description: 'Получите свою первую карту дня', icon: '🌟', order: 1 },
  { code: 'READINGS_10', name: 'Постоянный гость', description: 'Получите 10 раскладов', icon: '📚', order: 2 },
  { code: 'READINGS_50', name: 'Искатель истины', description: 'Получите 50 раскладов', icon: '🔮', order: 3 },
  { code: 'READINGS_100', name: 'Мастер Таро', description: 'Получите 100 раскладов', icon: '👑', order: 4 },
  { code: 'STREAK_7', name: 'Неделя мудрости', description: 'Получайте карту дня 7 дней подряд', icon: '🔥', order: 5 },
  { code: 'STREAK_30', name: 'Месяц познания', description: 'Получайте карту дня 30 дней подряд', icon: '⚡', order: 6 },
  { code: 'STREAK_100', name: 'Легенда', description: 'Получайте карту дня 100 дней подряд', icon: '💎', order: 7 },
  { code: 'COLLECTION_22', name: 'Старшие Арканы', description: 'Соберите все 22 карты Старших Арканов', icon: '🃏', order: 8 },
  { code: 'COLLECTION_78', name: 'Полная колода', description: 'Соберите все 78 карт Таро', icon: '🏆', order: 9 },
]

async function main() {
  console.log('Starting seed...')

  // Seed cards
  console.log('Seeding cards...')
  for (const card of cards) {
    await prisma.card.upsert({
      where: { slug: card.slug },
      update: card,
      create: card,
    })
  }
  console.log(`Created ${cards.length} cards`)

  // Seed achievements
  console.log('Seeding achievements...')
  for (const achievement of achievements) {
    await prisma.achievement.upsert({
      where: { code: achievement.code },
      update: achievement,
      create: achievement,
    })
  }
  console.log(`Created ${achievements.length} achievements`)

  console.log('Seed completed successfully!')
}

main()
  .catch((e) => {
    console.error('Seed error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
